services:
    Mobility:
      name: "Mobility"
      oldName: "Mobility"
      icons: ['mobility']
    Network_L1_3:
      name: "Network L1-3"
      oldName: "Network L1-3"
      icons: ['network_l_1-3']
    Network_L4:
      name: "Network L4+"
      oldName: "Network L4"
      icons: ['network_l_4']
    VoIP_Call_Control:
      name: "VoIP Call Control"
      oldName: "VoIP Call Control"
      icons: ['call_controll']
resources:
  NetworkLayer23:
    name: "Network L2-3"
    oldName: "Network Layer 2-3"
    subcategories: 
      Router:
          name: "Router"
          oldName: "Router"
          icons: ['router','vRouter']
      Gateway:
          name: "Gateway"
          oldName: "Gateway"
          icons: ['gateway']
      WAN_Connectors:
          name: "WAN Connectors"
          oldName: "WAN Connectors"
          icons: ['network','connector','port']
      LAN_Connectors:
          name: "LAN Connectors"
          oldName: "LAN Connectors"
          icons: ['network','connector','port']
      Infrastructure:
          name: "Infrastructure"
          icons: ['ucpe']
  NetworkLayer4:
    name: "Network L4+"
    oldName: "Network Layer 4+"
    subcategories: 
      Common_Network_Resources:
          name: "Common Network Resources"
          oldName: "Common Network Resources"
          icons: ['network']
  ApplicationLayer4:
    name: "Application L4+"
    oldName: "Application Layer 4+"
    subcategories: 
      Border_Element:
          name: "Border Element"
          oldName: "Border Elements"
          icons: ['borderElement']
      Application_Server:
          name: "Application Server"
          oldName: "Application Servers"
          icons: ['applicationServer']
      Web_Server:
          name: "Web Server"
          oldName: "Web Server"
          icons: ['applicationServer']
      Call_Control:
          name: "Call Control"
          oldName: "Call Control"
          icons: ['call_controll']
      Media_Servers:
          name: "Media Servers"
          oldName: "Media Servers"
          icons: ['applicationServer']
      Load_Balancer:
          name: "Load Balancer"
          oldName: "Load Balancer"
          icons: ['loadBalancer']
      Database:
          name: "Database"
          oldName: "Database"
          icons: ['database']
      Firewall:
          name: "Firewall"
          icons: ['firewall']
  Generic:
    name: "Generic"
    oldName: "Generic"
    subcategories: 
      Infrastructure:
          name: "Infrastructure"
          oldName: "Infrastructure"
          icons: ['connector']
      Abstract:
          name: "Abstract"
          oldName: "Abstract"
          icons: ['objectStorage', 'compute']
      Network_Elements:
          name: "Network Elements"
          oldName: "Network Elements"
          icons: ['network', 'connector']
      Database:
          name: "Database"
          oldName: "Database"
          icons: ['database']
  NetworkConnectivity:
    name: "Network Connectivity"
    subcategories:
      ConnectionPoints:
          name: "Connection Points"
          icons: ['cp']
      VirtualLinks:
          name: "Virtual Links"
          icons: ['vl']