tosca_definitions_version: tosca_simple_yaml_1_0_0
node_types: 
  tosca.nodes.Container.Application:
    derived_from: tosca.nodes.Root
    requirements:
      - host: 
          capability: tosca.capabilities.Container
          node: tosca.nodes.Container
          relationship: tosca.relationships.HostedOn
